from typing import Dict

from ..models.bone_group_mapping import BoneGroupMapping

DEFAULT_MAPPING: Dict[str, Dict[str, BoneGroupMapping]] = {
    "Default": {
        "Hair": BoneGroupMapping(
            [19],
            {
                "bone_05D9": "",
                "bone_0083": "",
                "bone_0084": "",
                "bone_0085": "",
                "bone_0086": "",
                "bone_0087": "",
                "bone_0088": "",
                "bone_012F": "",
                "bone_05D7": "",
                "bone_05D8": "",
                "bone_05DA": "",
                "bone_05DB": "",
                "bone_05DC": "",
                "bone_05DD": "",
                "bone_05DE": "",
                "bone_05E9": "",
                "bone_05EA": "",
                "bone_0012": "",
            },
        ),
        "Wings": BoneGroupMapping(
            [8],
            {
                "bone_0122": "",
                "bone_011E": "",
                "bone_011F": "",
                "bone_03C3": "",
                "bone_03C5": "",
                "bone_03C7": "",
                "bone_0124": "",
                "bone_0126": "",
                "bone_03C9": "",
                "bone_03CB": "",
                "bone_03CD": "",
                "bone_015A": "",
                "bone_015C": "",
                "bone_03CF": "",
                "bone_03D1": "",
                "bone_03D4": "",
                "bone_015E": "",
                "bone_0160": "",
                "bone_03D5": "",
                "bone_03D7": "",
                "bone_03D9": "",
                "bone_0162": "",
                "bone_03DB": "",
                "bone_03DD": "",
                "bone_03DF": "",
                "bone_03C1": "",
                "bone_0123": "",
                "bone_0120": "",
                "bone_0121": "",
                "bone_03C4": "",
                "bone_03C6": "",
                "bone_03C8": "",
                "bone_0125": "",
                "bone_0127": "",
                "bone_03CA": "",
                "bone_03CC": "",
                "bone_03CE": "",
                "bone_015B": "",
                "bone_015D": "",
                "bone_03D0": "",
                "bone_03D2": "",
                "bone_03D3": "",
                "bone_015F": "",
                "bone_0161": "",
                "bone_03D6": "",
                "bone_03D8": "",
                "bone_03DA": "",
                "bone_0163": "",
                "bone_03DC": "",
                "bone_03DE": "",
                "bone_03E0": "",
                "bone_03C2": "",
            },
        ),
        "Body Flaps": BoneGroupMapping(
            [24],
            {
                "bone_00A3": "",
                "bone_00B1": "",
                "bone_00B3": "",
                "bone_00BE": "",
                "bone_00A7": "",
                "bone_00BF": "",
                "bone_00B8": "",
                "bone_019C": "",
                "bone_00BA": "",
                "bone_019F": "",
                "bone_00BC": "",
                "bone_01B8": "",
                "bone_01BC": "",
                "bone_01CB": "",
                "bone_01C6": "",
                "bone_00A5": "",
                "bone_00A6": "",
                "bone_00BD": "",
                "bone_00B5": "",
                "bone_00C0": "",
                "bone_00B7": "",
                "bone_019A": "",
                "bone_00A9": "",
                "bone_019D": "",
                "bone_00AA": "",
                "bone_01B6": "",
                "bone_01B9": "",
                "bone_01BF": "",
                "bone_01C4": "",
                "bone_00B4": "",
                "bone_00B6": "",
                "bone_00AB": "",
                "bone_00A8": "",
                "bone_00AC": "",
                "bone_00B9": "",
                "bone_019B": "",
                "bone_00BB": "",
                "bone_019E": "",
                "bone_00B0": "",
                "bone_01B7": "",
                "bone_01BB": "",
                "bone_01C0": "",
                "bone_01C5": "",
                "bone_01A3": "",
                "bone_01A5": "",
                "bone_01AF": "",
                "bone_01A7": "",
                "bone_01B0": "",
                "bone_01A9": "",
                "bone_01B2": "",
                "bone_01AB": "",
                "bone_01B4": "",
                "bone_01AD": "",
                "bone_01BA": "",
                "bone_01BD": "",
                "bone_01C2": "",
                "bone_01C7": "",
                "bone_01A4": "",
                "bone_01A6": "",
                "bone_01AE": "",
                "bone_01A8": "",
                "bone_01B1": "",
                "bone_01AA": "",
                "bone_01B3": "",
                "bone_01AC": "",
                "bone_01B5": "",
                "bone_01A1": "",
                "bone_01C1": "",
                "bone_01BE": "",
                "bone_01C3": "",
                "bone_01C8": "",
                "bone_00A4": "",
                "bone_01CA": "",
                "bone_01E0": "",
                "bone_01D1": "",
                "bone_01E4": "",
                "bone_01D2": "",
                "bone_01E8": "",
                "bone_01D6": "",
                "bone_01EB": "",
                "bone_01C9": "",
                "bone_0210": "",
                "bone_0217": "",
                "bone_021E": "",
                "bone_0225": "",
                "bone_01CC": "",
                "bone_01DD": "",
                "bone_01CF": "",
                "bone_01E1": "",
                "bone_01D4": "",
                "bone_01E5": "",
                "bone_01D8": "",
                "bone_01F3": "",
                "bone_01DB": "",
                "bone_020D": "",
                "bone_0214": "",
                "bone_021B": "",
                "bone_0222": "",
                "bone_01EE": "",
                "bone_01FE": "",
                "bone_0257": "",
                "bone_01F7": "",
                "bone_0256": "",
                "bone_01FA": "",
                "bone_0253": "",
                "bone_01FD": "",
                "bone_01ED": "",
                "bone_0213": "",
                "bone_021A": "",
                "bone_0221": "",
                "bone_0228": "",
                "bone_01F0": "",
                "bone_024E": "",
                "bone_01F1": "",
                "bone_01F5": "",
                "bone_0254": "",
                "bone_01F8": "",
                "bone_0251": "",
                "bone_01FB": "",
                "bone_0250": "",
                "bone_0211": "",
                "bone_0218": "",
                "bone_021F": "",
                "bone_0226": "",
            },
        ),
        "Body Fins": BoneGroupMapping(
            [25],
            {
                "bone_008C": "",
                "bone_008D": "",
                "bone_0089": "",
                "bone_008A": "",
                "bone_008E": "",
                "bone_008F": "",
                "bone_0090": "",
                "bone_0091": "",
            },
        ),
    },
}
