from typing import Dict

from ...models.bone_group_mapping import BoneGroupMapping

SEOLBIM_MAPPING: Dict[str, Dict[str, BoneGroupMapping]] = {
    "Seolbim": {
        "Hair": BoneGroupMapping(
            [19],
            {"bone_0012": "", "bone_05ED": "", "bone_05EC": ""},
        ),
        "Head Accessories": BoneGroupMapping(
            [9],
            {"bone_2EEF": ""},
        ),
        "Shoe Laces": BoneGroupMapping(
            [9],
            {"bone_09ED": "", "bone_09EF": ""},
        ),
        "Wings": BoneGroupMapping(
            [8],
            {
                "bone_0122": "",
                "bone_011E": "",
                "bone_011F": "",
                "bone_03C3": "",
                "bone_03C5": "",
                "bone_03C7": "",
                "bone_0124": "",
                "bone_0126": "",
                "bone_03C9": "",
                "bone_03CB": "",
                "bone_03CD": "",
                "bone_015A": "",
                "bone_015C": "",
                "bone_03CF": "",
                "bone_03D1": "",
                "bone_03D4": "",
                "bone_015E": "",
                "bone_0160": "",
                "bone_03D5": "",
                "bone_03D7": "",
                "bone_03D9": "",
                "bone_0162": "",
                "bone_03DB": "",
                "bone_03DD": "",
                "bone_03DF": "",
                "bone_03C1": "",
                "bone_0123": "",
                "bone_0120": "",
                "bone_0121": "",
                "bone_03C4": "",
                "bone_03C6": "",
                "bone_03C8": "",
                "bone_0125": "",
                "bone_0127": "",
                "bone_03CA": "",
                "bone_03CC": "",
                "bone_03CE": "",
                "bone_015B": "",
                "bone_015D": "",
                "bone_03D0": "",
                "bone_03D2": "",
                "bone_03D3": "",
                "bone_015F": "",
                "bone_0161": "",
                "bone_03D6": "",
                "bone_03D8": "",
                "bone_03DA": "",
                "bone_0163": "",
                "bone_03DC": "",
                "bone_03DE": "",
                "bone_03E0": "",
                "bone_03C2": "",
            },
        ),
        "Skirt": BoneGroupMapping(
            [24],
            {
                "bone_0235": "",
                "bone_021C": "",
                "bone_0203": "",
                "bone_0257": "",
                "bone_01DA": "",
                "bone_01CB": "",
                "bone_01A9": "",
                "bone_0236": "",
                "bone_021D": "",
                "bone_0204": "",
                "bone_0256": "",
                "bone_01DB": "",
                "bone_01C2": "",
                "bone_01AA": "",
                "bone_0238": "",
                "bone_021E": "",
                "bone_0205": "",
                "bone_0255": "",
                "bone_01DC": "",
                "bone_01C3": "",
                "bone_01AB": "",
                "bone_0239": "",
                "bone_021F": "",
                "bone_0206": "",
                "bone_0254": "",
                "bone_01DD": "",
                "bone_01C4": "",
                "bone_01AC": "",
                "bone_00A6": "",
                "bone_023A": "",
                "bone_0220": "",
                "bone_0207": "",
                "bone_0253": "",
                "bone_01DE": "",
                "bone_01C5": "",
                "bone_01AD": "",
                "bone_00A7": "",
                "bone_023B": "",
                "bone_0221": "",
                "bone_0208": "",
                "bone_0252": "",
                "bone_01E9": "",
                "bone_01C6": "",
                "bone_01AE": "",
                "bone_00A8": "",
                "bone_023C": "",
                "bone_0222": "",
                "bone_0209": "",
                "bone_0251": "",
                "bone_01E0": "",
                "bone_01C7": "",
                "bone_01AF": "",
                "bone_00A9": "",
                "bone_023D": "",
                "bone_0223": "",
                "bone_020A": "",
                "bone_0250": "",
                "bone_01E1": "",
                "bone_01C8": "",
                "bone_01B0": "",
                "bone_00AA": "",
                "bone_023E": "",
                "bone_0224": "",
                "bone_020B": "",
                "bone_024F": "",
                "bone_01E2": "",
                "bone_01C9": "",
                "bone_01B1": "",
                "bone_023F": "",
                "bone_0225": "",
                "bone_020C": "",
                "bone_024E": "",
                "bone_01E3": "",
                "bone_01CA": "",
                "bone_01B2": "",
                "bone_0240": "",
                "bone_0226": "",
                "bone_020D": "",
                "bone_01F4": "",
                "bone_01E4": "",
                "bone_01D5": "",
                "bone_01B3": "",
                "bone_0241": "",
                "bone_0227": "",
                "bone_020E": "",
                "bone_01FE": "",
                "bone_01E5": "",
                "bone_01CC": "",
                "bone_01B4": "",
                "bone_0242": "",
                "bone_0228": "",
                "bone_020F": "",
                "bone_01F5": "",
                "bone_01E6": "",
                "bone_01CD": "",
                "bone_01B5": "",
                "bone_0243": "",
                "bone_0229": "",
                "bone_0210": "",
                "bone_01F6": "",
                "bone_01E7": "",
                "bone_01CE": "",
                "bone_01B6": "",
                "bone_0244": "",
                "bone_022A": "",
                "bone_0211": "",
                "bone_01F7": "",
                "bone_01E8": "",
                "bone_01CF": "",
                "bone_01B7": "",
                "bone_0245": "",
                "bone_022B": "",
                "bone_0212": "",
                "bone_01F8": "",
                "bone_01F3": "",
                "bone_01D0": "",
                "bone_01B8": "",
                "bone_019F": "",
                "bone_0246": "",
                "bone_022C": "",
                "bone_0213": "",
                "bone_01F9": "",
                "bone_01EA": "",
                "bone_01D1": "",
                "bone_01BA": "",
                "bone_01A0": "",
                "bone_0247": "",
                "bone_022D": "",
                "bone_0214": "",
                "bone_01FA": "",
                "bone_01EB": "",
                "bone_01D2": "",
                "bone_01C1": "",
                "bone_01A1": "",
                "bone_0248": "",
                "bone_022E": "",
                "bone_0215": "",
                "bone_01FB": "",
                "bone_01EC": "",
                "bone_01D3": "",
                "bone_01B9": "",
                "bone_01A2": "",
                "bone_0249": "",
                "bone_022F": "",
                "bone_0216": "",
                "bone_01FC": "",
                "bone_01ED": "",
                "bone_01D4": "",
                "bone_01BB": "",
                "bone_01A3": "",
                "bone_024A": "",
                "bone_0230": "",
                "bone_0217": "",
                "bone_01FD": "",
                "bone_01EE": "",
                "bone_01DF": "",
                "bone_01BC": "",
                "bone_01A4": "",
                "bone_024B": "",
                "bone_0231": "",
                "bone_0218": "",
                "bone_01FF": "",
                "bone_01EF": "",
                "bone_01D6": "",
                "bone_01BD": "",
                "bone_024C": "",
                "bone_0232": "",
                "bone_0219": "",
                "bone_0200": "",
                "bone_01F0": "",
                "bone_01D7": "",
                "bone_01BE": "",
                "bone_024D": "",
                "bone_0233": "",
                "bone_021A": "",
                "bone_0201": "",
                "bone_01F1": "",
                "bone_01D8": "",
                "bone_01BF": "",
                "bone_02B2": "",
                "bone_0234": "",
                "bone_021B": "",
                "bone_0202": "",
                "bone_01F2": "",
                "bone_01D9": "",
                "bone_01C0": "",
            },
        ),
        "Ribbons": BoneGroupMapping(
            [9],
            {
                "bone_09D3": "",
                "bone_09D6": "",
                "bone_09D9": "",
                "bone_09DC": "",
                "bone_09DF": "",
                "bone_09E2": "",
                "bone_09E5": "",
                "bone_09E8": "",
                "bone_09EB": "",
                "bone_09EE": "",
            },
        ),
    },
}
