from typing import Dict

from ...models.bone_group_mapping import BoneGroupMapping

ZHUQUE_MAPPING: Dict[str, Dict[str, BoneGroupMapping]] = {
    "Zhuque": {
        "Hair": BoneGroupMapping(
            [19],
            {
                "bone_0012": "",  # forehead
                "bone_0B3D": "",
                "bone_0B3E": "",
                "bone_0B47": "",
                "bone_0B48": "",
            },
        ),
        "Wings": BoneGroupMapping(
            [8],
            {
                "bone_011E": "",
                "bone_011F": "",
                "bone_0120": "",
                "bone_0121": "",
                "bone_0122": "",
                "bone_0123": "",
                "bone_0124": "",
                "bone_0125": "",
                "bone_0126": "",
                "bone_0127": "",
                "bone_015A": "",
                "bone_015B": "",
                "bone_015C": "",
                "bone_015D": "",
                "bone_015E": "",
                "bone_015F": "",
                "bone_0160": "",
                "bone_0161": "",
                "bone_0162": "",
                "bone_0163": "",
                "bone_03C1": "",
                "bone_03C2": "",
                "bone_03C3": "",
                "bone_03C4": "",
                "bone_03C5": "",
                "bone_03C6": "",
                "bone_03C7": "",
                "bone_03C8": "",
                "bone_03C9": "",
                "bone_03CA": "",
                "bone_03CB": "",
                "bone_03CC": "",
                "bone_03CD": "",
                "bone_03CE": "",
                "bone_03CF": "",
                "bone_03D0": "",
                "bone_03D1": "",
                "bone_03D2": "",
                "bone_03D3": "",
                "bone_03D4": "",
                "bone_03D5": "",
                "bone_03D6": "",
                "bone_03D7": "",
                "bone_03D8": "",
                "bone_03D9": "",
                "bone_03DA": "",
                "bone_03DB": "",
                "bone_03DC": "",
                "bone_03DD": "",
                "bone_03DE": "",
                "bone_03DF": "",
                "bone_03E0": "",
            },
        ),
        "Body Flaps": BoneGroupMapping(
            [24],
            {
                "bone_00A3": "",
                "bone_00A4": "",
                "bone_00A5": "",
                "bone_00A6": "",
                "bone_00A7": "",
                "bone_00A8": "",
                "bone_00A9": "",
                "bone_00AA": "",
                "bone_00AB": "",
                "bone_00AC": "",
                "bone_00B0": "",
                "bone_00B1": "",
                "bone_00B3": "",
                "bone_00B4": "",
                "bone_00B5": "",
                "bone_00B6": "",
                "bone_00B7": "",
                "bone_00B8": "",
                "bone_00B9": "",
                "bone_00BA": "",
                "bone_00BB": "",
                "bone_00BC": "",
                "bone_00BD": "",
                "bone_00BE": "",
                "bone_00BF": "",
                "bone_00C0": "",
                "bone_019A": "",
                "bone_019B": "",
                "bone_019C": "",
                "bone_019D": "",
                "bone_019E": "",
                "bone_019F": "",
                "bone_01A1": "",
                "bone_01A3": "",
                "bone_01A4": "",
                "bone_01A5": "",
                "bone_01A6": "",
                "bone_01A7": "",
                "bone_01A8": "",
                "bone_01A9": "",
                "bone_01AA": "",
                "bone_01AB": "",
                "bone_01AC": "",
                "bone_01AD": "",
                "bone_01AE": "",
                "bone_01AF": "",
                "bone_01B0": "",
                "bone_01B1": "",
                "bone_01B2": "",
                "bone_01B3": "",
                "bone_01B4": "",
                "bone_01B5": "",
                "bone_01B6": "",
                "bone_01B7": "",
                "bone_01B8": "",
                "bone_01B9": "",
                "bone_01BA": "",
                "bone_01BB": "",
                "bone_01BC": "",
                "bone_01BD": "",
                "bone_01BE": "",
                "bone_01BF": "",
                "bone_01C0": "",
                "bone_01C1": "",
                "bone_01C2": "",
                "bone_01C3": "",
                "bone_01C4": "",
                "bone_01C5": "",
                "bone_01C6": "",
                "bone_01C7": "",
                "bone_01C8": "",
                "bone_01CB": "",
                "bone_01D6": "",
                "bone_01D7": "",
                "bone_01D8": "",
                "bone_01D9": "",
                "bone_01DA": "",
                "bone_01DD": "",
                "bone_01DE": "",
                "bone_01E0": "",
                "bone_01E1": "",
                "bone_01E4": "",
                "bone_01E5": "",
                "bone_01E6": "",
                "bone_01E7": "",
                "bone_01E8": "",
                "bone_01E9": "",
                "bone_01EB": "",
                "bone_01EC": "",
                "bone_01ED": "",
                "bone_01EE": "",
                "bone_01EF": "",
                "bone_01F2": "",
                "bone_01F4": "",
                "bone_01F6": "",
                "bone_01F7": "",
                "bone_01F8": "",
                "bone_01F9": "",
                "bone_01FA": "",
                "bone_01FD": "",
                "bone_01FF": "",
                "bone_0200": "",
                "bone_0201": "",
                "bone_0202": "",
                "bone_0205": "",
                "bone_0206": "",
                "bone_0207": "",
                "bone_0208": "",
                "bone_0209": "",
                "bone_020C": "",
                "bone_020D": "",
                "bone_020E": "",
                "bone_020F": "",
                "bone_0210": "",
                "bone_0213": "",
                "bone_0214": "",
                "bone_0215": "",
                "bone_0216": "",
                "bone_0217": "",
                "bone_021A": "",
                "bone_021B": "",
                "bone_021C": "",
                "bone_021D": "",
                "bone_021E": "",
                "bone_0221": "",
                "bone_0222": "",
                "bone_0223": "",
                "bone_0224": "",
                "bone_0225": "",
                "bone_0228": "",
                "bone_0229": "",
                "bone_022A": "",
                "bone_022B": "",
                "bone_022C": "",
                "bone_022F": "",
                "bone_0230": "",
                "bone_0231": "",
                "bone_0232": "",
                "bone_0233": "",
                "bone_0236": "",
                "bone_0238": "",
                "bone_0239": "",
                "bone_023A": "",
                "bone_023B": "",
                "bone_023E": "",
                "bone_023F": "",
                "bone_0240": "",
                "bone_0241": "",
                "bone_0242": "",
                "bone_024E": "",
                "bone_024F": "",
                "bone_0250": "",
                "bone_0251": "",
                "bone_0254": "",
                "bone_0255": "",
                "bone_0256": "",
                "bone_0257": "",
                "bone_1013": "",
                "bone_1014": "",
                "bone_1015": "",
                "bone_1016": "",
                "bone_1017": "",
            },
        ),
        "Body Fins": BoneGroupMapping(
            [25],
            {
                "bone_0089": "",
                "bone_008A": "",
                "bone_008E": "",
                "bone_008F": "",
                "bone_0090": "",
                "bone_0091": "",
            },
        ),
        "Arm Flaps": BoneGroupMapping(
            [26],
            {
                "bone_0ABC": "",
                "bone_0ABD": "",
            },
        ),
        "Head Accessories": BoneGroupMapping(
            [9],
            {
                "bone_0B4D": "",
                "bone_0B4E": "",
                "bone_0F6C": "",
                "bone_0F6D": "",
            },
        ),
    },
}
