from typing import Dict

from owm_additions.bones.bone_group_mapping import BoneGroupMapping

AVIATOR_MAPPING: Dict[str, Dict[str, BoneGroupMapping]] = {
    "Aviator": {
        "Hair": BoneGroupMapping(
            [19],
            {
                "bone_05DA": "",
                "bone_05DB": "",
                "bone_05DC": "",
                "bone_01EA": "",
                "bone_01E2": "",
                "bone_01DA": "",
                "bone_01EB": "",
                "bone_01E3": "",
                "bone_01DB": "",
                "bone_01EC": "",
                "bone_01E4": "",
                "bone_01DC": "",
                "bone_01ED": "",
                "bone_01E5": "",
                "bone_01DD": "",
                "bone_01EE": "",
                "bone_01E6": "",
                "bone_01DE": "",
                "bone_01F1": "",
                "bone_01F3": "",
                "bone_01E1": "",
                # beads
                "bone_07B3": "",
                "bone_07B4": "",
                "bone_07B5": "",
                "bone_01E7": "",
                "bone_01E9": "",
                "bone_01F0": "",
                "bone_01E8": "",
                "bone_01E0": "",
            },
        ),
        "Wings": BoneGroupMapping(
            [8],
            {},
        ),
        "Jacket": BoneGroupMapping(
            [24],
            {
                "bone_01C2": "",
                "bone_01B2": "",
                "bone_01A1": "",
                "bone_00A3": "",
                "bone_01C3": "",
                "bone_01B3": "",
                "bone_01A2": "",
                "bone_00A4": "",
                "bone_01C4": "",
                "bone_01B4": "",
                "bone_01A3": "",
                "bone_00A5": "",
                "bone_01C5": "",
                "bone_01B5": "",
                "bone_01A4": "",
                "bone_00A6": "",
                "bone_01C6": "",
                "bone_01B6": "",
                "bone_01A5": "",
                "bone_00A7": "",
                "bone_01C7": "",
                "bone_01B7": "",
                "bone_01A6": "",
                "bone_00A8": "",
                "bone_01C8": "",
                "bone_01B8": "",
                "bone_01A7": "",
                "bone_00A9": "",
                "bone_01C9": "",
                "bone_01BA": "",
                "bone_01A8": "",
                "bone_00AA": "",
                "bone_01CA": "",
                "bone_01C1": "",
                "bone_01A9": "",
                "bone_00AB": "",
                "bone_01D5": "",
                "bone_01B9": "",
                "bone_01AA": "",
                "bone_00AC": "",
                "bone_01CC": "",
                "bone_01BB": "",
                "bone_01AB": "",
                "bone_019A": "",
                "bone_01CD": "",
                "bone_01BC": "",
                "bone_01AC": "",
                "bone_019B": "",
                "bone_01CE": "",
                "bone_01BD": "",
                "bone_01AD": "",
                "bone_019C": "",
                "bone_01CF": "",
                "bone_01BE": "",
                "bone_01AE": "",
                "bone_019D": "",
                "bone_01D0": "",
                "bone_01BF": "",
                "bone_01AF": "",
                "bone_019E": "",
                "bone_01D1": "",
                "bone_01C0": "",
                "bone_01B0": "",
                "bone_019F": "",
                "bone_01D2": "",
                "bone_01CB": "",
                "bone_01B1": "",
                "bone_01A0": "",
            },
        ),
        "Body Fins": BoneGroupMapping(
            [25],
            {},
        ),
    },
}
