from typing import Dict, List

HERO_SKINS: Dict[str, List[str]] = {
    "Ana": [
        "Bastet",
        "Cabana",
        "Captain Amari",
        "Citrine",
        "Classic",
        "Corsair",
        "Cybermedic",
        "Garnet",
        "Ghoul",
        "Gingerbread",
        "Haroeris",
        "Horus",
        "Merciful",
        "Peridot",
        "Pharaoh",
        "Shrike",
        "Sniper",
        "Snow Owl",
        "Tal",
        "Turquoise",
        "Wadjet",
        "Wasteland",
    ],
    "Ashe": [
        "Classic",
        "Deadlock",
        "Gangster",
        "Jungle",
        "Little Red",
        "Mardi Gras",
        "Mobster",
        "Paintbrush",
        "Poolside",
        "Posh",
        "Safari",
        "Socialite",
        "Sunflower",
        "Tansy",
        "Thorn",
        "Tiger Huntress",
        "Warlock",
        "Winter",
        "Yucca",
    ],
    "Baptiste": [
        "Ble",
        "Buccaneer",
        "Camouflage",
        "Classic",
        "Combat Medic",
        "Desert Ops",
        "Funky",
        "Pirate",
        "Spec Ops",
        "Talon",
        "Terracotta Medic",
        "Tropical",
        "Vampire",
        "Vyolèt",
        "Vèt",
        "Wasteland",
        "Wouj",
    ],
    "Bastion": [
        "Antique",
        "Avalanche",
        "BlizzCon 2016",
        "Brick",
        "Classic",
        "Dawn",
        "Defense Matrix",
        "Dragonfire",
        "Dune Buggy",
        "Gearbot",
        "Gift Wrap",
        "Gwishin",
        "Meadow",
        "Null Sector",
        "Omnic Crisis",
        "Overgrown",
        "Rooster",
        "Sand Castle",
        "Sky",
        "Soot",
        "Stealth",
        "Steambot",
        "Tombstone",
        "Woodbot",
    ],
    "Brigitte": [
        "Blå",
        "Carbon Fiber",
        "Classic",
        "Engineer",
        "Feskarn",
        "General",
        "Goat",
        "Grön",
        "Ironclad",
        "Mechanic",
        "Máni",
        "Opera",
        "Plommon",
        "Riot Police",
        "Röd",
        "Shieldmaiden",
        "Stone",
        "Sól",
        "Tre Kronor",
        "Vampire Hunter",
    ],
    "D.Va": [
        "2020 Pacific All-Stars",
        "Academy",
        "B.Va",
        "Black Cat",
        "Blueberry",
        "Carbon Fiber",
        "Classic",
        "Cruiser",
        "Junebug",
        "Junker",
        "Lemon-Lime",
        "Midnight",
        "Nano",
        "Officer",
        "Palanquin",
        "Scavenger",
        "Shin-Ryeong",
        "Taegeukgi",
        "Tangerine",
        "Watermelon",
        "Waveracer",
        "White Rabbit",
    ],
    "Doomfist": [
        "Avatar",
        "Blackhand",
        "Carbon Fiber",
        "Caution",
        "Classic",
        "Daisy",
        "Formal",
        "Gladiator",
        "Irin",
        "Jötunn",
        "Karate",
        "Lake",
        "Leopard",
        "Monk",
        "Painted",
        "Plains",
        "Spirit",
        "Sunset",
        "Swamp Monster",
        "Talon",
        "Thunder",
    ],
    "Echo": [
        "Bird of Paradise",
        "Butterfly",
        "Camo",
        "Carbon Fiber",
        "Classic",
        "Durian",
        "Good and Evil",
        "Hot Rod",
        "Kkachi",
        "Marina",
        "Moth",
        "Papaya",
        "Ragdoll",
        "Stealth",
        "Surf's Up",
        "Vanda",
    ],
    "Genji": [
        "2018 Pacific All-Stars",
        "Azurite",
        "Baihu",
        "Bedouin",
        "Blackwatch",
        "Bushi",
        "Carbon Fiber",
        "Chrome",
        "Cinnabar",
        "Classic",
        "Illidan",
        "Karasu-Tengu",
        "Kendoka",
        "Malachite",
        "Nihon",
        "Nomad",
        "Ochre",
        "Oni",
        "Sentai",
        "Sparrow",
        "Young Genji",
    ],
    "Hanzo": [
        "Azuki",
        "Casual",
        "Classic",
        "Cloud",
        "Cyberninja",
        "Dai-Tengu",
        "Demon",
        "Dragon",
        "Huang Zhong",
        "Kabuki",
        "Kinoko",
        "Kyōgisha",
        "Lone Wolf",
        "Midori",
        "Nihon",
        "Okami",
        "Scion",
        "Sora",
        "Wave",
        "Young Hanzo",
        "Young Master",
    ],
    "Junkrat": [
        "Beachrat",
        "Bilgerat",
        "Bleached",
        "Caution",
        "Circus",
        "Classic",
        "Cricket",
        "Dr. Junkenstein",
        "Drowned",
        "Elf",
        "Firework",
        "Fool",
        "Hayseed",
        "Inferno",
        "Irradiated",
        "Jailbird",
        "Jester",
        "Junkfood",
        "King Jamison",
        "Krampus",
        "Rusted",
        "Scarecrow",
        "Toasted",
    ],
    "Lúcio": [
        "2019 Pacific All-Stars",
        "Andes",
        "Auditiva",
        "Azul",
        "Bitrate",
        "Breakaway",
        "Capoeira",
        "Classic",
        "Corredor",
        "Equalizer",
        "Gorgon",
        "Hippityhop",
        "Jazzy",
        "Laranja",
        "Ribbit",
        "Roxo",
        "Samul Nori",
        "Seleção",
        "Slapshot",
        "Snow Fox",
        "Striker",
        "Synaesthesia",
        "Vermelho",
    ],
    "McCree": [
        "American",
        "Blackwatch",
        "Classic",
        "Deadlock",
        "Ebony",
        "Gambler",
        "Lake",
        "Lifeguard",
        "Magistrate",
        "Masked Man",
        "Mountain Man",
        "Mystery Man",
        "On the Range",
        "Riverboat",
        "Royal",
        "Sage",
        "Scrooge",
        "Sherlock",
        "Undead",
        "Van Helsing",
        "Vigilante",
        "Wheat",
        "White Hat",
        "Xiake",
    ],
    "Mei": [
        "Abominable",
        "Bear",
        "Beekeeper",
        "Chang'e",
        "Chrysanthemum",
        "Classic",
        "Earthen",
        "Ecopoint_ Antarctica",
        "Firefighter",
        "Heliotrope",
        "Honeydew",
        "Jade",
        "Jiangshi",
        "Luna",
        "Mei-rry",
        "Pajamei",
        "Penguin",
        "Persimmon",
        "Pumpkin",
        "Rescue Mei",
        "Snow Plum",
        "Sprinkles",
        "Yeti Hunter",
        "Zhongguo",
    ],
    "Mercy": [
        "2019 Atlantic All-Stars",
        "Amber",
        "Camouflage",
        "Celestial",
        "Classic",
        "Cobalt",
        "Combat Medic Ziegler",
        "Devil",
        "Dr. Ziegler",
        "Dragoon",
        "Eidgenossin",
        "Fortune",
        "Imp",
        "Mage",
        "Mist",
        "Orchid",
        "Pink",
        "Royal Knight",
        "Seolbim",
        "Sigrún",
        "Snow Angel",
        "Sugar Plum Fairy",
        "Valkyrie",
        "Verdant",
        "Winged Victory",
        "Witch",
        "Zhuque",
    ],
    "Moira": [
        "Banshee",
        "Blackwatch",
        "Classic",
        "Fiery",
        "Glam",
        "Holly",
        "Ice Empress",
        "Mask Dancer",
        "Minister",
        "Moon",
        "Oasis",
        "Ornate",
        "Pale",
        "Royal",
        "Scientist",
        "Selkie",
        "Venus",
        "Whiskey",
        "Éireannach",
    ],
    "Orisa": [
        "Bull Demon",
        "Camouflage",
        "Carbon Fiber",
        "Classic",
        "Dawn",
        "Demon",
        "Dynastinae",
        "Forest Spirit",
        "Ice Cream",
        "Immortal",
        "Megasoma",
        "Null Sector",
        "OR15",
        "Plains",
        "Protector",
        "Referee",
        "Sanye",
        "Sunrise",
        "Twilight",
    ],
    "Pharah": [
        "Amethyst",
        "Anubis",
        "Asp",
        "Aviator",
        "Bedouin",
        "Carbon Fiber",
        "Classic",
        "Copper",
        "Emerald",
        "Enchanted Armor",
        "Frostbite",
        "Jackal",
        "Lifeguard",
        "Mechaqueen",
        "Orbital",
        "Possessed",
        "Qinglong",
        "Raindancer",
        "Raptorion",
        "Security Chief",
        "Sunset",
        "Thunderbird",
        "Titanium",
    ],
    "Reaper": [
        "American",
        "Biker",
        "Blackwatch Reyes",
        "Blood",
        "Classic",
        "Desert",
        "Dracula",
        "El Blanco",
        "Hellfire",
        "Imperial Guard",
        "Lü Bu",
        "Mariachi",
        "Masquerade",
        "Midnight",
        "Moss",
        "Nevermore",
        "Plague Doctor",
        "Pumpkin",
        "Rat King",
        "Royal",
        "Shiver",
        "Soldier_ 24",
        "Wight",
    ],
    "Reinhardt": [
        "2020 Atlantic All-Stars",
        "Balderich",
        "Blackhardt",
        "Bloodhardt",
        "Brass",
        "Bundesadler",
        "Bundeswehr",
        "Classic",
        "Cobalt",
        "Coldhardt",
        "Conductor",
        "Copper",
        "Crusader",
        "Festive",
        "Greifhardt",
        "Gridironhardt",
        "Guan Yu",
        "Lieutenant Wilhelm",
        "Lionhardt",
        "Paragon",
        "Raynhardt",
        "Stonehardt",
        "Viridian",
        "Wujing",
    ],
    "Roadhog": [
        "Bajie",
        "Butcher",
        "Classic",
        "Frosty",
        "Ice Fisherman",
        "Islander",
        "Junkenstein's Monster",
        "Kiwi",
        "Lacrosse",
        "Mako",
        "Midas",
        "Militia",
        "Mud",
        "Pachimari",
        "Pigpen",
        "Rudolph",
        "Sand",
        "Sharkbait",
        "Stitched",
        "Thistle",
        "Toa",
        "Toxic",
    ],
    "Sigma": [
        "Asylum",
        "Blauw",
        "Carbon Fiber",
        "Classic",
        "Dr. de Kuiper",
        "Flying Dutchman",
        "Groen",
        "Maestro",
        "Oracle",
        "Oranje",
        "Prophet",
        "Rime",
        "Roze",
        "Scuba",
        "Subject Sigma",
        "Talon",
    ],
    "Soldier: 76": [
        "Alpine: 76",
        "Bone",
        "Classic",
        "Commando: 76",
        "Cyborg: 76",
        "Daredevil: 76",
        "Formal: 76",
        "Golden",
        "Grillmaster: 76",
        "Immortal",
        "Jet",
        "Night Ops: 76",
        "Olive",
        "Russet",
        "Slasher: 76",
        "Smoke",
        "Soldier: 1776",
        "Strike Commander Morrison",
        "Stunt Rider: 76",
        "Ugly Sweater: 76",
        "Venom",
    ],
    "Sombra": [
        "Augmented",
        "Azúcar",
        "Black Cat",
        "Bride",
        "Cidro",
        "Classic",
        "Cyberspace",
        "Demon Hunter",
        "Face Changer",
        "Fantasma",
        "Glitch",
        "Incendio",
        "Los Muertos",
        "Mar",
        "Mexicana",
        "Noche",
        "Oro",
        "Peppermint",
        "Rime",
        "Talon",
        "Tulum",
        "Virus",
    ],
    "Symmetra": [
        "Architech",
        "Cardamom",
        "Classic",
        "Devi",
        "Dragon",
        "Figure Skater",
        "Goddess",
        "Holi",
        "Hyacinth",
        "Magician",
        "Marammat",
        "Mermaid",
        "Oasis",
        "Peacock",
        "Qipao",
        "Regal",
        "Saffron",
        "Technomancer",
        "Tyrande",
        "Utopaea",
        "Vampire",
        "Vishkar",
    ],
    "Torbjörn": [
        "Barbarossa",
        "Blackbeard",
        "Blå",
        "Cathode",
        "Chief Engineer Lindholm",
        "Chopper",
        "Citron",
        "Classic",
        "Cybjörn",
        "Deadlock",
        "Grön",
        "Ironclad",
        "Lumberjack",
        "Magni",
        "Plommon",
        "Rustclad",
        "Santaclad",
        "Surf 'n' Splash",
        "Tre Kronor",
        "Viking",
        "Woodclad",
        "Zhang Fei",
    ],
    "Tracer": [
        "2018 Atlantic All-Stars",
        "Cadet Oxton",
        "Cavalry",
        "Classic",
        "Comic Book",
        "Electric Purple",
        "Graffiti",
        "Hong Gildong",
        "Hot Pink",
        "Jingle",
        "Lightning",
        "Mach T",
        "Neon Green",
        "Nezha",
        "Posh",
        "Punk",
        "Rose",
        "Royal Blue",
        "Slipstream",
        "Sporty",
        "Sprinter",
        "T. Racer",
        "Track and Field",
        "Ultraviolet",
        "Union Jack",
        "Will-o'-Wisp",
    ],
    "Widowmaker": [
        "Ange de la mort",
        "Biathlon",
        "Black Lily",
        "Ciel",
        "Classic",
        "Comtesse",
        "Côte d'Azur",
        "Electric",
        "Fleur de Lis",
        "Huntress",
        "Kerrigan",
        "Mousquetaire",
        "Noire",
        "Nova",
        "Nuit",
        "Odette",
        "Odile",
        "Pale Serpent",
        "Patina",
        "Rose",
        "Scorpion",
        "Spider",
        "Talon",
        "Tricolore",
        "Vert",
        "Winter",
    ],
    "Winston": [
        "Ancient Bronze",
        "Atmosphere",
        "Banana",
        "BlizzCon 2017",
        "Catcher",
        "Classic",
        "Desert",
        "Explorer",
        "Flying Ace",
        "Forest",
        "Frogston",
        "Gargoyle",
        "Horizon",
        "Ocean King",
        "Red Planet",
        "Safari",
        "Specimen 28",
        "Undersea",
        "Werewolf",
        "Wukong",
        "Yeti",
    ],
    "Wrecking Ball": [
        "8 Ball",
        "Biohazard",
        "Chloride",
        "Classic",
        "High Roller",
        "Horizon",
        "Jack-o'-lantern",
        "Junker",
        "Lithium",
        "Lunar",
        "Lúcioball",
        "Mayham",
        "Paper Cutting",
        "Potassium",
        "Smoke",
        "Submarine",
        "Wooden Ball",
    ],
    "Zarya": [
        "Alien",
        "Arctic",
        "Barbarian",
        "Brick",
        "Champion",
        "Classic",
        "Cybergoth",
        "Cyberian",
        "Dawn",
        "Einherjar",
        "Frosted",
        "Goldenrod",
        "Industrial",
        "Midnight",
        "Polyanitsa",
        "Racer",
        "Siberian Front",
        "Snowboarder",
        "Taiga",
        "Totally 80's",
        "Violet",
        "Weightlifter",
        "Workout",
        "Xuanwu",
    ],
    "Zenyatta": [
        "Air",
        "Ascendant",
        "Carbon Fiber",
        "Classic",
        "Cultist",
        "Djinnyatta",
        "Earth",
        "Fastball",
        "Harmonious",
        "Huitzilopochtli",
        "Ifrit",
        "Leaf",
        "Nutcracker",
        "Ra",
        "Sanzang",
        "Skullyatta",
        "Subaquatic",
        "Sunyatta",
        "Toybot",
        "Water",
        "Zen-nakji",
        "Zhuge Liang",
    ],
}

HERO_UNICODED: Dict[str, str] = {"Lcio": "Lúcio", "Torbjrn": "Torbjörn"}

SKIN_UNICODED: Dict[str, str] = {
    "Vyolt": "Vyolèt",
    "Vt": "Vèt",
    "Bl": "Blå",
    "Grn": "Grön",
    "Mni": "Máni",
    "Rd": "Röd",
    "Sl": "Sól",
    "Jtunn": "Jötunn",
    "Kygisha": "Kyōgisha",
    "Seleo": "Seleção",
    "Sigrn": "Sigrún",
    "ireannach": "Éireannach",
    "L Bu": "Lü Bu",
    "Azcar": "Azúcar",
    "Cybjrn": "Cybjörn",
    "Cte d'Azur": "Côte d'Azur",
    "Lcioball": "Lúcioball",
}
