from typing import Dict

from ...bone_group_mapping import BoneGroupMapping

WINGED_VICTORY_MAPPING: Dict[str, Dict[str, BoneGroupMapping]] = {
    "Winged Victory": {
        "Hair": BoneGroupMapping(
            layers=[19],
            bones={
                "bone_0012": "Winged Victory Crown",
                "bone_0083": "bone_0083",
                "bone_0087": "bone_0087",
                "bone_0088": "bone_0088",
                "bone_05D9": "bone_05D9",
                "bone_05EA": "Mercy Ponytail Root",
                "bone_05EB": "Mercy Ponytail 0",
                "bone_05EC": "Mercy Ponytail 1",
                "bone_05ED": "Mercy Ponytail 2",
            },
        ),
        "Wings": BoneGroupMapping(
            layers=[8],
            bones={
                "bone_011E": "bone_011E",
                "bone_011F": "bone_011F",
                "bone_0120": "bone_0120",
                "bone_0121": "bone_0121",
                "bone_0124": "bone_0124",
                "bone_0125": "bone_0125",
                "bone_0126": "bone_0126",
                "bone_0127": "bone_0127",
                "bone_015A": "bone_015A",
                "bone_015B": "bone_015B",
                "bone_015C": "bone_015C",
                "bone_015D": "bone_015D",
                "bone_015E": "bone_015E",
                "bone_015F": "bone_015F",
                "bone_0160": "bone_0160",
                "bone_0161": "bone_0161",
                "bone_0162": "bone_0162",
                "bone_0163": "bone_0163",
                "bone_03C1": "bone_03C1",
                "bone_03C2": "bone_03C2",
                "bone_03C3": "bone_03C3",
                "bone_03C4": "bone_03C4",
                "bone_03C5": "bone_03C5",
                "bone_03C6": "bone_03C6",
                "bone_03C7": "bone_03C7",
                "bone_03C8": "bone_03C8",
                "bone_03C9": "bone_03C9",
                "bone_03CA": "bone_03CA",
                "bone_03CB": "bone_03CB",
                "bone_03CC": "bone_03CC",
                "bone_03CD": "bone_03CD",
                "bone_03CE": "bone_03CE",
                "bone_03CF": "bone_03CF",
                "bone_03D0": "bone_03D0",
                "bone_03D1": "bone_03D1",
                "bone_03D2": "bone_03D2",
                "bone_03D3": "bone_03D3",
                "bone_03D4": "bone_03D4",
                "bone_03D5": "bone_03D5",
                "bone_03D6": "bone_03D6",
                "bone_03D7": "bone_03D7",
                "bone_03D8": "bone_03D8",
                "bone_03D9": "bone_03D9",
                "bone_03DA": "bone_03DA",
                "bone_03DB": "bone_03DB",
                "bone_03DC": "bone_03DC",
                "bone_03DD": "bone_03DD",
                "bone_03DE": "bone_03DE",
                "bone_03DF": "bone_03DF",
                "bone_03E0": "bone_03E0",
            },
        ),
        "Skirt": BoneGroupMapping(
            layers=[24],
            bones={
                "bone_00A3": "Torso Front Anchor",
                "bone_00A4": "Torso Back Anchor",
                "bone_00A5": "Winged Victory Dress Front R 1 15",
                "bone_00A6": "Winged Victory Dress Front R 0 15",
                "bone_00A7": "Winged Victory Dress Front 15",
                "bone_00A8": "Winged Victory Dress Front L 0 15",
                "bone_00A9": "Winged Victory Dress Front L 1 15",
                "bone_00AA": "Winged Victory Dress Front R 1 14",
                "bone_00AB": "Winged Victory Dress Front R 0 14",
                "bone_00AC": "Winged Victory Dress Front 14",
                "bone_019A": "Winged Victory Dress Front L 0 14",
                "bone_019B": "Winged Victory Dress Front L 1 14",
                "bone_019C": "Winged Victory Dress Back L 2 13",
                "bone_019D": "Winged Victory Dress Back L 1 13",
                "bone_019E": "Winged Victory Dress Back L 0 13",
                "bone_019F": "Winged Victory Dress Back 13",
                "bone_01A1": "Winged Victory Dress Back R 0 13",
                "bone_01A2": "Winged Victory Dress Back R 1 13",
                "bone_01A3": "Winged Victory Dress Back R 2 13",
                "bone_01A4": "Winged Victory Dress Front R 1 13",
                "bone_01A5": "Winged Victory Dress Front R 0 13",
                "bone_01A6": "Winged Victory Dress Front 13",
                "bone_01A7": "Winged Victory Dress Front L 0 13",
                "bone_01A8": "Winged Victory Dress Front L 1 13",
                "bone_01A9": "Winged Victory Dress Back L 2 12",
                "bone_01AA": "Winged Victory Dress Back L 1 12",
                "bone_01AB": "Winged Victory Dress Back L 0 12",
                "bone_01AC": "Winged Victory Dress Back 12",
                "bone_01AD": "Winged Victory Dress Back R 0 12",
                "bone_01AE": "Winged Victory Dress Back R 1 12",
                "bone_01AF": "Winged Victory Dress Back R 2 12",
                "bone_01B0": "Winged Victory Dress Front R 1 12",
                "bone_01B1": "Winged Victory Dress Front R 0 12",
                "bone_01B2": "Winged Victory Dress Front 12",
                "bone_01B3": "Winged Victory Dress Front L 0 12",
                "bone_01B4": "Winged Victory Dress Front L 1 12",
                "bone_01B5": "Winged Victory Dress Back L 2 11",
                "bone_01B6": "Winged Victory Dress Back L 1 11",
                "bone_01B7": "Winged Victory Dress Back L 0 11",
                "bone_01B8": "Winged Victory Dress Back 11",
                "bone_01B9": "Winged Victory Dress Back R 2 11",
                "bone_01BA": "Winged Victory Dress Back R 0 11",
                "bone_01BB": "Winged Victory Dress Front R 1 11",
                "bone_01BC": "Winged Victory Dress Front R 0 11",
                "bone_01BD": "Winged Victory Dress Front 11",
                "bone_01BE": "Winged Victory Dress Front L 0 11",
                "bone_01BF": "Winged Victory Dress Front L 1 11",
                "bone_01C0": "Winged Victory Dress Back L 2 10",
                "bone_01C1": "Winged Victory Dress Back R 1 11",
                "bone_01C2": "Winged Victory Dress Back L 0 10",
                "bone_01C3": "Winged Victory Dress Back 10",
                "bone_01C4": "Winged Victory Dress Back R 0 10",
                "bone_01C5": "Winged Victory Dress Back R 1 10",
                "bone_01C6": "Winged Victory Dress Back R 2 10",
                "bone_01C7": "Winged Victory Dress Front R 1 10",
                "bone_01C8": "Winged Victory Dress Front R 0 10",
                "bone_01C9": "Winged Victory Dress Front 10",
                "bone_01CA": "Winged Victory Dress Front L 0 10",
                "bone_01CB": "Winged Victory Dress Back L 1 10",
                "bone_01CC": "Winged Victory Dress Back L 2 9",
                "bone_01CD": "Winged Victory Dress Back L 1 9",
                "bone_01CE": "Winged Victory Dress Back L 0 9",
                "bone_01CF": "Winged Victory Dress Back 9",
                "bone_01D0": "Winged Victory Dress Back R 0 9",
                "bone_01D1": "Winged Victory Dress Back R 1 9",
                "bone_01D2": "Winged Victory Dress Back R 2 9",
                "bone_01D3": "Winged Victory Dress Front R 1 9",
                "bone_01D4": "Winged Victory Dress Front R 0 9",
                "bone_01D5": "Winged Victory Dress Front L 1 10",
                "bone_01D6": "Winged Victory Dress Front L 0 9",
                "bone_01D7": "Winged Victory Dress Front L 1 9",
                "bone_01D8": "Winged Victory Dress Back L 2 8",
                "bone_01D9": "Winged Victory Dress Back L 1 8",
                "bone_01DA": "Winged Victory Dress Back L 0 8",
                "bone_01DB": "Winged Victory Dress Back 8",
                "bone_01DC": "Winged Victory Dress Back R 0 8",
                "bone_01DD": "Winged Victory Dress Back R 1 8",
                "bone_01DE": "Winged Victory Dress Back R 2 8",
                "bone_01DF": "Winged Victory Dress Front 9",
                "bone_01E0": "Winged Victory Dress Front R 0 8",
                "bone_01E1": "Winged Victory Dress Front 8",
                "bone_01E2": "Winged Victory Dress Front L 0 8",
                "bone_01E3": "Winged Victory Dress Front L 1 8",
                "bone_01E4": "Winged Victory Dress Back L 2 7",
                "bone_01E5": "Winged Victory Dress Back L 1 7",
                "bone_01E6": "Winged Victory Dress Back L 0 7",
                "bone_01E7": "Winged Victory Dress Back 7",
                "bone_01E8": "Winged Victory Dress Back R 0 7",
                "bone_01E9": "Winged Victory Dress Front R 1 8",
                "bone_01EA": "Winged Victory Dress Back R 2 7",
                "bone_01EB": "Winged Victory Dress Front R 1 7",
                "bone_01EC": "Winged Victory Dress Front R 0 7",
                "bone_01ED": "Winged Victory Dress Front 7",
                "bone_01EE": "Winged Victory Dress Front L 0 7",
                "bone_01EF": "Winged Victory Dress Front L 1 7",
                "bone_01F0": "Winged Victory Dress Back L 2 6",
                "bone_01F1": "Winged Victory Dress Back L 1 6",
                "bone_01F2": "Winged Victory Dress Back L 0 6",
                "bone_01F3": "Winged Victory Dress Back R 1 7",
                "bone_01F4": "Winged Victory Dress Back L 1 5",
                "bone_01F5": "Winged Victory Dress Back 5",
                "bone_01F6": "Winged Victory Dress Back R 0 5",
                "bone_01F7": "Winged Victory Dress Back R 1 5",
                "bone_01F8": "Winged Victory Dress Back R 2 5",
                "bone_01F9": "Winged Victory Dress Front R 1 5",
                "bone_01FA": "Winged Victory Dress Front R 0 5",
                "bone_01FB": "Winged Victory Dress Front 5",
                "bone_01FC": "Winged Victory Dress Front L 0 5",
                "bone_01FD": "Winged Victory Dress Front L 1 5",
                "bone_01FE": "Winged Victory Dress Back L 0 5",
                "bone_01FF": "Winged Victory Dress Back L 2 4",
                "bone_0200": "Winged Victory Dress Back L 1 4",
                "bone_0201": "Winged Victory Dress Back L 0 4",
                "bone_0204": "Winged Victory Dress Back 4",
                "bone_0205": "Winged Victory Dress Back R 0 4",
                "bone_0206": "Winged Victory Dress Back R 1 4",
                "bone_0207": "Winged Victory Dress Back R 2 4",
                "bone_020A": "Winged Victory Dress Front R 1 4",
                "bone_020B": "Winged Victory Dress Front R 0 4",
                "bone_020C": "Winged Victory Dress Front 4",
                "bone_020D": "Winged Victory Dress Front L 0 4",
                "bone_020E": "Winged Victory Dress Front L 1 4",
                "bone_020F": "Winged Victory Dress Side L 4 3",
                "bone_0210": "Winged Victory Dress Side L 5 3",
                "bone_0211": "Winged Victory Dress Back L 2 3",
                "bone_0212": "Winged Victory Dress Back L 1 3",
                "bone_0213": "Winged Victory Dress Back L 0 3",
                "bone_0214": "Winged Victory Dress Back 3",
                "bone_0215": "Winged Victory Dress Back R 0 3",
                "bone_0216": "Winged Victory Dress Back R 1 3",
                "bone_0217": "Winged Victory Dress Back R 2 3",
                "bone_0218": "Winged Victory Dress Side R 5 3",
                "bone_0219": "Winged Victory Dress Side R 4 3",
                "bone_021A": "Winged Victory Dress Side R 3 3",
                "bone_021B": "Winged Victory Dress Side R 2 3",
                "bone_021C": "Winged Victory Dress Side R 1 3",
                "bone_021D": "Winged Victory Dress Side R 0 3",
                "bone_021E": "Winged Victory Dress Front R 1 3",
                "bone_021F": "Winged Victory Dress Front R 0 3",
                "bone_0220": "Winged Victory Dress Front 3",
                "bone_0221": "Winged Victory Dress Front L 0 3",
                "bone_0222": "Winged Victory Dress Front L 1 3",
                "bone_0223": "Winged Victory Dress Side L 0 3",
                "bone_0224": "Winged Victory Dress Side L 1 3",
                "bone_0225": "Winged Victory Dress Side L 2 3",
                "bone_0226": "Winged Victory Dress Side L 3 3",
                "bone_0227": "Winged Victory Dress Side L 4 2",
                "bone_0228": "Winged Victory Dress Side L 5 2",
                "bone_0229": "Winged Victory Dress Back L 2 2",
                "bone_022C": "Winged Victory Dress Back L 1 2",
                "bone_022D": "Winged Victory Dress Back L 0 2",
                "bone_022E": "Winged Victory Dress Back 2",
                "bone_022F": "Winged Victory Dress Back R 0 2",
                "bone_0232": "Winged Victory Dress Back R 1 2",
                "bone_0233": "Winged Victory Dress Back R 2 2",
                "bone_0234": "Winged Victory Dress Side R 5 2",
                "bone_0235": "Winged Victory Dress Side R 4 2",
                "bone_0239": "Winged Victory Dress Side R 3 2",
                "bone_023A": "Winged Victory Dress Side R 2 2",
                "bone_023B": "Winged Victory Dress Side R 1 2",
                "bone_023C": "Winged Victory Dress Side R 0 2",
                "bone_023F": "Winged Victory Dress Front R 1 2",
                "bone_0240": "Winged Victory Dress Front R 0 2",
                "bone_0241": "Winged Victory Dress Front 2",
                "bone_0242": "Winged Victory Dress Front L 0 2",
                "bone_0245": "Winged Victory Dress Front L 1 2",
                "bone_0246": "Winged Victory Dress Side L 0 2",
                "bone_0247": "Winged Victory Dress Side L 1 2",
                "bone_0248": "Winged Victory Dress Side L 2 2",
                "bone_024B": "Winged Victory Dress Side L 3 2",
                "bone_024C": "Winged Victory Dress Side L 4 1",
                "bone_024D": "Winged Victory Dress Side L 5 1",
                "bone_024E": "Winged Victory Dress Back L 2 5",
                "bone_024F": "Winged Victory Dress Front L 1 6",
                "bone_0250": "Winged Victory Dress Front L 0 6",
                "bone_0251": "Winged Victory Dress Front 6",
                "bone_0252": "Winged Victory Dress Front R 0 6",
                "bone_0253": "Winged Victory Dress Front R 1 6",
                "bone_0254": "Winged Victory Dress Back R 2 6",
                "bone_0255": "Winged Victory Dress Back R 1 6",
                "bone_0256": "Winged Victory Dress Back R 0 6",
                "bone_0257": "Winged Victory Dress Back 6",
                "bone_0258": "Winged Victory Dress Back R 2 1",
                "bone_0259": "Winged Victory Dress Side R 5 1",
                "bone_025A": "Winged Victory Dress Side R 4 1",
                "bone_025D": "Winged Victory Dress Side R 3 1",
                "bone_025E": "Winged Victory Dress Side R 2 1",
                "bone_025F": "Winged Victory Dress Side R 1 1",
                "bone_0260": "Winged Victory Dress Side R 0 1",
                "bone_0263": "Winged Victory Dress Front R 1 1",
                "bone_0264": "Winged Victory Dress Front R 0 1",
                "bone_0265": "Winged Victory Dress Front 1",
                "bone_0266": "Winged Victory Dress Front L 0 1",
                "bone_0269": "Winged Victory Dress Front L 1 1",
                "bone_026A": "Winged Victory Dress Side L 0 1",
                "bone_026B": "Winged Victory Dress Side L 1 1",
                "bone_026C": "Winged Victory Dress Side L 2 1",
                "bone_026F": "Winged Victory Dress Side L 3 1",
                "bone_0270": "Winged Victory Dress Side L 4 0",
                "bone_0271": "Winged Victory Dress Side L 5 0",
                "bone_0272": "Winged Victory Dress Back L 2 0",
                "bone_0280": "Winged Victory Dress Back L 0 0",
                "bone_0281": "Winged Victory Dress Back 0",
                "bone_0282": "Winged Victory Dress Back R 0 0",
                "bone_0283": "Winged Victory Dress Back R 1 0",
                "bone_0284": "Winged Victory Dress Back R 2 0",
                "bone_0285": "Winged Victory Dress Side R 5 0",
                "bone_0286": "Winged Victory Dress Side R 4 0",
                "bone_0287": "Winged Victory Dress Side R 3 0",
                "bone_0288": "Winged Victory Dress Side R 2 0",
                "bone_0289": "Winged Victory Dress Back L 1 0",
                "bone_028A": "Winged Victory Dress Side R 0 0",
                "bone_028B": "Winged Victory Dress Front R 1 0",
                "bone_028C": "Winged Victory Dress Front R 0 0",
                "bone_028D": "Winged Victory Dress Front 0",
                "bone_028E": "Winged Victory Dress Front L 0 0",
                "bone_028F": "Winged Victory Dress Front L 1 0",
                "bone_0290": "Winged Victory Dress Side L 0 0",
                "bone_0291": "Winged Victory Dress Side L 1 0",
                "bone_0292": "Winged Victory Dress Side L 2 0",
                "bone_0293": "Winged Victory Dress Side R 1 0",
                "bone_029D": "Winged Victory Dress Side L 3 0",
                "bone_02B2": "Winged Victory Dress Back L 2 1",
                "bone_02B5": "Winged Victory Dress Back L 1 1",
                "bone_02B6": "Winged Victory Dress Back L 0 1",
                "bone_02B7": "Winged Victory Dress Back 1",
                "bone_02B8": "Winged Victory Dress Back R 0 1",
                "bone_02BB": "Winged Victory Dress Back R 1 1",
            },
        ),
        "Body Fins": BoneGroupMapping(
            layers=[25],
            bones={
                "bone_0089": "",
                "bone_008A": "",
                "bone_008C": "",
                "bone_008D": "",
                "bone_008E": "",
                "bone_008F": "",
                "bone_0090": "",
                "bone_0091": "",
            },
        ),
        "Ribbons": BoneGroupMapping(
            layers=[9],
            bones={
                "bone_0122": "Mercy Wing Root L",
                "bone_0123": "Mercy Wing Root R",
                "bone_02CB": "Winged Victory Back Ribbon L Inner 0",
                "bone_02CC": "Winged Victory Back Ribbon L 0",
                "bone_02CD": "Winged Victory Back Ribbon L Outer 0",
                "bone_02CE": "Winged Victory Back Ribbon L Inner 1",
                "bone_02CF": "Winged Victory Back Ribbon L 1",
                "bone_02D0": "Winged Victory Back Ribbon L Outer 1",
                "bone_02D1": "Winged Victory Back Ribbon L Inner 2",
                "bone_02D2": "Winged Victory Back Ribbon L 2",
                "bone_02D3": "Winged Victory Back Ribbon L Outer 2",
                "bone_02D4": "Winged Victory Back Ribbon L Inner 3",
                "bone_02D5": "Winged Victory Back Ribbon L 3",
                "bone_02D6": "Winged Victory Back Ribbon L Outer 3",
                "bone_02D7": "Winged Victory Back Ribbon L Inner 4",
                "bone_02D8": "Winged Victory Back Ribbon L 4",
                "bone_02D9": "Winged Victory Back Ribbon L Outer 4",
                "bone_02DA": "Winged Victory Back Ribbon L Inner 5",
                "bone_02DB": "Winged Victory Back Ribbon L Inner 6",
                "bone_02DC": "Winged Victory Back Ribbon L 5",
                "bone_02DD": "Winged Victory Back Ribbon L 6",
                "bone_02DE": "Winged Victory Back Ribbon L Outer 6",
                "bone_02DF": "Winged Victory Back Ribbon L Inner 7",
                "bone_02E0": "Winged Victory Back Ribbon L 7",
                "bone_02E1": "Winged Victory Back Ribbon L Outer 7",
                "bone_02E2": "Winged Victory Back Ribbon L Inner 8",
                "bone_02E3": "Winged Victory Back Ribbon L Outer 5",
                "bone_02E4": "Winged Victory Back Ribbon L Outer 8",
                "bone_02E5": "Winged Victory Back Ribbon L Inner 9",
                "bone_02E6": "Winged Victory Back Ribbon L 9",
                "bone_02E7": "Winged Victory Back Ribbon L Outer 9",
                "bone_02E8": "Winged Victory Back Ribbon L Inner 10",
                "bone_02E9": "Winged Victory Back Ribbon L 10",
                "bone_02EA": "Winged Victory Back Ribbon L Outer 10",
                "bone_02EB": "Winged Victory Back Ribbon L Inner 11",
                "bone_02EC": "Winged Victory Back Ribbon L 11",
                "bone_02ED": "Winged Victory Back Ribbon L 8",
                "bone_02EE": "Winged Victory Back Ribbon L Inner 12",
                "bone_02EF": "Winged Victory Back Ribbon L 12",
                "bone_02F0": "Winged Victory Back Ribbon L Outer 12",
                "bone_02F7": "Winged Victory Back Ribbon L Outer 11",
                "bone_02F8": "Winged Victory Back Ribbon R 0",
                "bone_02F9": "Winged Victory Back Ribbon R Outer 0",
                "bone_02FA": "Winged Victory Back Ribbon R Inner 1",
                "bone_02FB": "Winged Victory Back Ribbon R 1",
                "bone_02FC": "Winged Victory Back Ribbon R Outer 1",
                "bone_02FD": "Winged Victory Back Ribbon R Inner 2",
                "bone_02FE": "Winged Victory Back Ribbon R 2",
                "bone_02FF": "Winged Victory Back Ribbon R Outer 2",
                "bone_0300": "Winged Victory Back Ribbon R Inner 3",
                "bone_0301": "Winged Victory Back Ribbon R Inner 0",
                "bone_0302": "Winged Victory Back Ribbon R Outer 3",
                "bone_0303": "Winged Victory Back Ribbon R Inner 4",
                "bone_0304": "Winged Victory Back Ribbon R 4",
                "bone_0305": "Winged Victory Back Ribbon R Outer 4",
                "bone_0306": "Winged Victory Back Ribbon R Inner 5",
                "bone_0307": "Winged Victory Back Ribbon R 5",
                "bone_0308": "Winged Victory Back Ribbon R Outer 5",
                "bone_0309": "Winged Victory Back Ribbon R Inner 6",
                "bone_030A": "Winged Victory Back Ribbon R 6",
                "bone_030B": "Winged Victory Back Ribbon R 3",
                "bone_030C": "Winged Victory Back Ribbon R Inner 7",
                "bone_030D": "Winged Victory Back Ribbon R 7",
                "bone_030E": "Winged Victory Back Ribbon R Outer 7",
                "bone_030F": "Winged Victory Back Ribbon R Inner 8",
                "bone_0310": "Winged Victory Back Ribbon R 8",
                "bone_0311": "Winged Victory Back Ribbon R Outer 8",
                "bone_0312": "Winged Victory Back Ribbon R Inner 9",
                "bone_0313": "Winged Victory Back Ribbon R 9",
                "bone_0314": "Winged Victory Back Ribbon R Outer 9",
                "bone_0315": "Winged Victory Back Ribbon R Outer 6",
                "bone_0320": "Winged Victory Front Ribbon L 4",
                "bone_0321": "Winged Victory Front Ribbon L Outer 4",
                "bone_0322": "Winged Victory Front Ribbon L Inner 3",
                "bone_0323": "Winged Victory Front Ribbon L 3",
                "bone_0324": "Winged Victory Front Ribbon L Outer 3",
                "bone_0325": "Winged Victory Front Ribbon L Inner 2",
                "bone_0326": "Winged Victory Front Ribbon L 2",
                "bone_0327": "Winged Victory Front Ribbon L Outer 2",
                "bone_0328": "Winged Victory Front Ribbon L Inner 1",
                "bone_0329": "Winged Victory Front Ribbon L 1",
                "bone_032A": "Winged Victory Front Ribbon L Outer 1",
                "bone_032B": "Winged Victory Front Ribbon L Inner 0",
                "bone_032C": "Winged Victory Front Ribbon L 0",
                "bone_032D": "Winged Victory Front Ribbon L Outer 0",
                "bone_0334": "Winged Victory Front Ribbon R Inner 4",
                "bone_0335": "Winged Victory Front Ribbon R 4",
                "bone_0336": "Winged Victory Front Ribbon R Outer 4",
                "bone_0337": "Winged Victory Front Ribbon R Inner 3",
                "bone_0338": "Winged Victory Front Ribbon R 3",
                "bone_0339": "Winged Victory Front Ribbon R Outer 3",
                "bone_033A": "Winged Victory Front Ribbon R Inner 2",
                "bone_033B": "Winged Victory Front Ribbon R 2",
                "bone_033C": "Winged Victory Front Ribbon R Outer 2",
                "bone_033D": "Winged Victory Front Ribbon R Inner 1",
                "bone_033E": "Winged Victory Front Ribbon R 1",
                "bone_033F": "Winged Victory Front Ribbon R 0",
                "bone_0340": "Winged Victory Front Ribbon R Outer 1",
                "bone_0341": "Winged Victory Front Ribbon R Outer 0",
                "bone_0347": "Winged Victory Front Ribbon R Inner 0",
                "bone_037A": "Winged Victory Back Ribbon R Inner 10",
                "bone_037B": "Winged Victory Back Ribbon R 10",
                "bone_037C": "Winged Victory Back Ribbon R Outer 10",
                "bone_037D": "Winged Victory Back Ribbon R Inner 11",
                "bone_037E": "Winged Victory Back Ribbon R 11",
                "bone_037F": "Winged Victory Back Ribbon R Outer 11",
                "bone_0380": "Winged Victory Back Ribbon R Inner 12",
                "bone_0381": "Winged Victory Back Ribbon R 12",
                "bone_0382": "Winged Victory Back Ribbon R Outer 12",
                "bone_0383": "Winged Victory Front Ribbon L Inner 4",
            },
        ),
        "Ropes": BoneGroupMapping(
            layers=[9],
            bones={
                "bone_04F2": "Winged Victory Ropes Root",
                "bone_04F4": "Winged Victory Ropes Front 0",
                "bone_04F6": "Winged Victory Ropes Front 1",
                "bone_04F8": "Winged Victory Ropes Front 2",
                "bone_04FA": "Winged Victory Ropes Back 0",
                "bone_04FC": "Winged Victory Ropes Back 1",
                "bone_04FE": "Winged Victory Ropes Back 2",
            },
        ),
    },
}
