from typing import Dict

from ...bone_group_mapping import BoneGroupMapping

BASE_MAPPING: Dict[str, Dict[str, BoneGroupMapping]] = {
    "Base": {
        # in Classic
        "Hair": BoneGroupMapping(
            [19],
            {
                "bone_0012": "Halo",
                "bone_0083": "1-2",
                "bone_0084": "1-3",
                "bone_0085": "1-4",
                "bone_0086": "Root 2",
                "bone_0087": "2-1",
                "bone_0088": "2-2",
                "bone_012F": "2-3",
                "bone_05D7": "Root 3",
                "bone_05D8": "3-1",
                "bone_05D9": "Root 1",
                "bone_05DA": "3-2",
                "bone_05DB": "3-3",
                "bone_05DC": "Root 4",
                "bone_05DD": "4-1",
                "bone_05DE": "Ponytail",
                "bone_05E9": "Top Root",
                "bone_05EA": "Top",
            },
        ),
        "Body Fins": BoneGroupMapping(
            [25],
            {
                "bone_0089": "Front L 2",
                "bone_008A": "Front R 2",
                "bone_008C": "Front L 1",
                "bone_008D": "Front R 1",
                "bone_008E": "Front L 3",
                "bone_008F": "Front R 3",
                "bone_0090": "Back L",
                "bone_0091": "Back R",
            },
        ),
        # in all
        "Wings": BoneGroupMapping(
            [8],
            {
                "bone_011E": "",
                "bone_011F": "",
                "bone_0120": "",
                "bone_0121": "",
                "bone_0122": "",
                "bone_0123": "",
                "bone_0124": "",
                "bone_0125": "",
                "bone_0126": "",
                "bone_0127": "",
                "bone_015A": "",
                "bone_015B": "",
                "bone_015C": "",
                "bone_015D": "",
                "bone_015E": "",
                "bone_015F": "",
                "bone_0160": "",
                "bone_0161": "",
                "bone_0162": "",
                "bone_0163": "",
                "bone_03C1": "",  # not found in all
                "bone_03C2": "",  # not found in all
                "bone_03C3": "",
                "bone_03C4": "",
                "bone_03C5": "",
                "bone_03C6": "",
                "bone_03C7": "",
                "bone_03C8": "",
                "bone_03C9": "",
                "bone_03CA": "",
                "bone_03CB": "",
                "bone_03CC": "",
                "bone_03CD": "",
                "bone_03CE": "",
                "bone_03CF": "",
                "bone_03D0": "",
                "bone_03D1": "",
                "bone_03D2": "",
                "bone_03D3": "",
                "bone_03D4": "",
                "bone_03D5": "",
                "bone_03D6": "",
                "bone_03D7": "",
                "bone_03D8": "",
                "bone_03D9": "",
                "bone_03DA": "",
                "bone_03DB": "",
                "bone_03DC": "",
                "bone_03DD": "",
                "bone_03DE": "",
                "bone_03DF": "",
                "bone_03E0": "",
            },
        ),
    },
}
