from typing import Dict

from ...bone_group_mapping import BoneGroupMapping

WITCH_MAPPING: Dict[str, Dict[str, BoneGroupMapping]] = {
    "Witch": {
        "Accessories": BoneGroupMapping(
            [9],
            {
                "bone_04F2": "",
                "bone_04F3": "",
                "bone_04F4": "",
                "bone_0592": "",
                "bone_0731": "",
            },
        ),
        "Body Flaps": BoneGroupMapping(
            [24],
            {
                "bone_00A3": "",
                "bone_00A4": "",
                "bone_00A5": "",
                "bone_00A6": "",
                "bone_00A7": "",
                "bone_00A8": "",
                "bone_00A9": "",
                "bone_00AA": "",
                "bone_00AB": "",
                "bone_00AC": "",
                "bone_019A": "",
                "bone_019B": "",
                "bone_019C": "",
                "bone_019D": "",
                "bone_019E": "",
                "bone_019F": "",
                "bone_01A0": "",
                "bone_01A1": "",
                "bone_01A2": "",
                "bone_01A3": "",
                "bone_01A4": "",
                "bone_01A5": "",
                "bone_01A6": "",
                "bone_01A7": "",
                "bone_01A8": "",
                "bone_01A9": "",
                "bone_01AA": "",
                "bone_01AB": "",
                "bone_01AC": "",
                "bone_01AD": "",
                "bone_01AE": "",
                "bone_01AF": "",
                "bone_01B0": "",
                "bone_01B1": "",
                "bone_01B2": "",
                "bone_01B3": "",
                "bone_01B4": "",
                "bone_01B5": "",
                "bone_01B6": "",
                "bone_01B7": "",
                "bone_01B8": "",
                "bone_01B9": "",
                "bone_01BA": "",
                "bone_01BB": "",
                "bone_01BC": "",
                "bone_01BD": "",
                "bone_01BE": "",
                "bone_01BF": "",
                "bone_01C0": "",
                "bone_01C1": "",
                "bone_01C2": "",
                "bone_01C3": "",
                "bone_01C4": "",
                "bone_01C5": "",
                "bone_01C6": "",
                "bone_01C7": "",
                "bone_01C8": "",
                "bone_01C9": "",
                "bone_01CA": "",
                "bone_01CB": "",
                "bone_01CC": "",
                "bone_01CD": "",
                "bone_01CE": "",
                "bone_01CF": "",
                "bone_01D0": "",
                "bone_01D1": "",
                "bone_01D2": "",
                "bone_01D3": "",
                "bone_01D4": "",
                "bone_01D5": "",
                "bone_01D6": "",
                "bone_01D7": "",
                "bone_01D8": "",
                "bone_01D9": "",
                "bone_01DA": "",
                "bone_01DB": "",
                "bone_01DC": "",
                "bone_01DD": "",
                "bone_01DE": "",
                "bone_01DF": "",
                "bone_01E0": "",
                "bone_01E1": "",
                "bone_01E2": "",
                "bone_01E3": "",
                "bone_01E4": "",
                "bone_01E5": "",
                "bone_01E6": "",
                "bone_01E7": "",
                "bone_01E8": "",
                "bone_01E9": "",
                "bone_01EA": "",
                "bone_01F3": "",
                "bone_021A": "",
                "bone_021B": "",
                "bone_021C": "",
                "bone_021D": "",
                "bone_021E": "",
                "bone_021F": "",
                "bone_0220": "",
                "bone_0221": "",
                "bone_0222": "",
                "bone_0223": "",
                "bone_022A": "",
                "bone_022B": "",
                "bone_022C": "",
            },
        ),
        "Arm Flaps": BoneGroupMapping(
            [25],
            {
                "bone_009B": "",
                "bone_009C": "",
                "bone_01EF": "",
                "bone_01F0": "",
                "bone_01F1": "",
                "bone_01F4": "",
                "bone_01F5": "",
                "bone_01F6": "",
                "bone_01F7": "",
                "bone_01F9": "",
                "bone_01FA": "",
                "bone_01FB": "",
                "bone_01FC": "",
                "bone_0202": "",
                "bone_0203": "",
                "bone_0204": "",
                "bone_0206": "",
                "bone_0207": "",
                "bone_0208": "",
                "bone_020A": "",
                "bone_020B": "",
                "bone_020C": "",
                "bone_020E": "",
                "bone_020F": "",
                "bone_0210": "",
                "bone_0212": "",
                "bone_0213": "",
                "bone_0214": "",
                "bone_0216": "",
                "bone_0217": "",
                "bone_0218": "",
                "bone_0219": "",
                "bone_024E": "",
                "bone_024F": "",
                "bone_0251": "",
                "bone_0252": "",
                "bone_0253": "",
                "bone_0255": "",
                "bone_0256": "",
                "bone_0257": "",
            },
        ),
        "Hair": BoneGroupMapping(
            [19],
            {
                "bone_0012": "",
                "bone_07B3": "",
                "bone_07B4": "",
            },
        ),
    },
}
